import styles from '../styles/Layout.module.css'
import Head from 'next/head'
import Navbar from '../components/Navbar/Navbar'

const Layout = ({ children }: any) => {
  return (
    <>
      <Head>
        <title>Meco :: chat</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='stylesheet'
          href='https://use.fontawesome.com/releases/v5.15.3/css/all.css'
          integrity='sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk'
          crossOrigin='anonymous'
        />
      </Head>

      <div className={styles.container}>
        <Navbar />
        <main>{children}</main>
        <footer className={styles.footer}>
          <h3>footer</h3>
        </footer>
      </div>
    </>
  )
}

export default Layout
